# Generated by Django 4.2.5 on 2023-09-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('weekday', models.CharField(blank=True, default=6, max_length=100)),
            ],
        ),
    ]
