# Generated by Django 4.2.5 on 2023-09-10 07:32

from django.db import migrations, models
import webservice_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice_api', '0003_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='greetings',
            field=models.CharField(blank=True, default=webservice_api.models.Welcome.get_greetings, max_length=300),
        ),
    ]
